'use client'
import Presentation from './content/presentation';
import Link from 'next/link'
export default function Home() {
  return (
     <div>
      <Presentation />
      <footer>
        <p style={{ textAlign: 'center', marginTop: '20px' }} className="text-sm text-gray-700">
          © 2025 History of AI Presentation. All rights reserved.
        </p>
        <p style={{ textAlign: 'center', marginTop: '2px' }} className="text-sm text-gray-700">
             Generated By Haider Hussain
        </p>
        <p style={{ textAlign: 'center', marginTop: '2px' }} className="text-sm text-gray-700">
          Github@<Link href="https://github.com/786haider" className="hover:text-blue-800">786haider</Link> | Email:<Link href="/" className="hover:text-blue-800" >haiderhussain536@gmail.com</Link>
          </p>
      </footer>
     </div>
  );
}
